# Generated by Django 4.2.7 on 2023-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_rename_id_cdf_official_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdf_official',
            name='id',
        ),
        migrations.AddField(
            model_name='cdf_official',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
