# Generated by Django 4.2.7 on 2023-11-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_remove_cdf_official_id_cdf_official_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdf_official',
            old_name='ID',
            new_name='id',
        ),
    ]
