# Generated by Django 4.2.7 on 2023-11-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0006_alter_cdfofficial_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdfofficial',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='cdfofficial',
            name='phone',
        ),
    ]
