# Generated by Django 4.2.7 on 2023-11-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0007_remove_cdfofficial_designation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cdfofficial',
            new_name='user',
        ),
    ]
