# Generated by Django 4.2.7 on 2023-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0008_rename_cdfofficial_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cdfofficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
