# Generated by Django 4.2.7 on 2023-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0009_cdfofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdfofficial',
            name='student',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
