# Generated by Django 4.2.7 on 2023-11-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0010_cdfofficial_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdfofficial',
            name='uSer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bursary.user'),
        ),
    ]
