# Generated by Django 4.2.7 on 2023-11-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0011_cdfofficial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdfofficial',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cdfofficial',
            name='student',
        ),
        migrations.AlterField(
            model_name='cdfofficial',
            name='uSer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bursary.user'),
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True)),
                ('student', models.CharField(max_length=255, null=True)),
                ('uSer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bursary.user')),
            ],
        ),
    ]
