# Generated by Django 4.2.7 on 2023-11-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0012_remove_cdfofficial_phone_remove_cdfofficial_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='uSer',
            new_name='school',
        ),
    ]
