# Generated by Django 4.2.7 on 2023-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0013_rename_user_institution_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
