# Generated by Django 4.2.7 on 2023-11-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0018_alter_institution_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='cheque',
        ),
        migrations.AddField(
            model_name='institution',
            name='Cheque',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
