# Generated by Django 4.2.7 on 2023-11-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0020_remove_institution_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='Cheque',
            field=models.ImageField(null=True,  upload_to=''),
        ),
    ]
