# Generated by Django 4.2.7 on 2023-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0027_rename_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Name',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
