# Generated by Django 4.2.7 on 2023-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0029_alter_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Name',
            field=models.CharField(default='Name your university here', max_length=255, null=True),
        ),
    ]
